package constants;

public enum WarningType {
    MISMATCH_HANDLER_UI,
    MISSING_PERMISSION,
    REDUNDANT_REQUEST,
    MISMATCH_REQUEST,
    NON_PRIVACY_PRESERVING,
    UNCLEAR_RATIONALE,
    NON_PRIVACY_PRESERVING_LOCATION
}
